version: '3.8'

services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
        container_name: todo-list-db
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        volumes:
            - db:/var/lib/mysql
        networks:
            - backend

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        container_name: todo-list-mdb
        volumes:
            - mongo-data:/data/db
        networks:
            - backend

    backend:
        build: ./backend
        restart: unless-stopped
        env_file: ./.env
        container_name: todo-list-backend
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            - DB_HOST=mysqldb
            - DB_USER=$MYSQLDB_USER
            - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - DB_NAME=$MYSQLDB_DATABASE
            - DB_PORT=$MYSQLDB_DOCKER_PORT
            - CLIENT_ORIGIN=$CLIENT_ORIGIN
        networks:
            - backend
            - frontend
        depends_on:
            - mongodb
            - mysqldb
        working_dir: /backend
        entrypoint: ['/bin/bash', './entrypoint.sh']

    frontend:
        build:
            context: ./frontend
            args:
                - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
        ports:
            - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
        networks:
            - frontend
        container_name: todo-list-frontend
        depends_on:
            - backend

volumes:
    db:
    mongo-data:

networks:
    backend:
    frontend:
